"""add_contour_model

Revision ID: 46acbbeef72f
Revises: b3dd3e5c4c94
Create Date: 2026-01-11 19:19:11.185989

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '46acbbeef72f'
down_revision = 'b3dd3e5c4c94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contours',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('network_id', sa.UUID(), nullable=False),
    sa.Column('station_id', sa.UUID(), nullable=True),
    sa.Column('field_strength_dbuvm', sa.Numeric(), nullable=False),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4674, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['core.networks.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['core.stations_v4.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    with op.batch_alter_table('contours', schema='core') as batch_op:
        batch_op.create_index('idx_contours_geom', ['geom'], unique=False, postgresql_using='gist')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contours', schema='core') as batch_op:
        batch_op.drop_index('idx_contours_geom', postgresql_using='gist')

    op.drop_table('contours', schema='core')
    # ### end Alembic commands ###
