"""Add V4 models

Revision ID: 5896fdaf3efb
Revises: 3b1d1f0c0a2f
Create Date: 2026-01-11 16:46:57.172814

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision = '5896fdaf3efb'
down_revision = '3b1d1f0c0a2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('antennas_v4',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('manufacturer', sa.Text(), nullable=True),
    sa.Column('gain_dbd', sa.Float(), nullable=False),
    sa.Column('tilt_el', sa.Float(), nullable=False),
    sa.Column('pattern_h', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pattern_v', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('rasters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('bbox', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4674, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('resolution_arcsec', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename'),
    schema='gis'
    )
    # with op.batch_alter_table('rasters', schema='gis') as batch_op:
    #     batch_op.create_index('idx_rasters_bbox', ['bbox'], unique=False, postgresql_using='gist')

    op.create_table('networks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('network_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['core.networks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('stations_v4',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('network_id', sa.UUID(), nullable=False),
    sa.Column('service', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('canal', sa.Integer(), nullable=True),
    sa.Column('freq_mhz', sa.Float(), nullable=True),
    sa.Column('uf', sa.Text(), nullable=True),
    sa.Column('municipio', sa.Text(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4674, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('h_eff', sa.Float(), nullable=True),
    sa.Column('htx', sa.Float(), nullable=True),
    sa.Column('d_max', sa.Float(), nullable=True),
    sa.Column('mosaico_id', sa.Text(), nullable=True),
    sa.Column('entidade', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['core.networks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    # with op.batch_alter_table('stations_v4', schema='core') as batch_op:
    #     batch_op.create_index('idx_stations_v4_geom', ['geom'], unique=False, postgresql_using='gist')

    with op.batch_alter_table('aerodromes', schema='anatel') as batch_op:
        batch_op.drop_index('idx_aerodromes_geom', postgresql_using='gist')
        batch_op.drop_index('idx_aerodromes_icao')

    with op.batch_alter_table('anatel_stations', schema='anatel') as batch_op:
        batch_op.drop_index('idx_anatel_stations_geom', postgresql_using='gist')
        batch_op.drop_index('idx_anatel_stations_service')

    with op.batch_alter_table('contours', schema='gis') as batch_op:
        batch_op.drop_index('idx_contours_geom', postgresql_using='gist')

    with op.batch_alter_table('interference_testpoints', schema='gis') as batch_op:
        batch_op.drop_index('idx_interference_testpoints_geom', postgresql_using='gist')

    with op.batch_alter_table('rni_critical_areas', schema='gis') as batch_op:
        batch_op.drop_index('idx_rni_critical_areas_geom', postgresql_using='gist')

    with op.batch_alter_table('rni_zones', schema='gis') as batch_op:
        batch_op.drop_index('idx_rni_zones_geom', postgresql_using='gist')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rni_zones', schema='gis') as batch_op:
        batch_op.create_index('idx_rni_zones_geom', ['geom'], unique=False, postgresql_using='gist')

    with op.batch_alter_table('rni_critical_areas', schema='gis') as batch_op:
        batch_op.create_index('idx_rni_critical_areas_geom', ['geom'], unique=False, postgresql_using='gist')

    with op.batch_alter_table('interference_testpoints', schema='gis') as batch_op:
        batch_op.create_index('idx_interference_testpoints_geom', ['geom'], unique=False, postgresql_using='gist')

    with op.batch_alter_table('contours', schema='gis') as batch_op:
        batch_op.create_index('idx_contours_geom', ['geom'], unique=False, postgresql_using='gist')

    with op.batch_alter_table('anatel_stations', schema='anatel') as batch_op:
        batch_op.create_index('idx_anatel_stations_service', ['service'], unique=False)
        batch_op.create_index('idx_anatel_stations_geom', ['geom'], unique=False, postgresql_using='gist')

    with op.batch_alter_table('aerodromes', schema='anatel') as batch_op:
        batch_op.create_index('idx_aerodromes_icao', ['icao'], unique=False)
        batch_op.create_index('idx_aerodromes_geom', ['geom'], unique=False, postgresql_using='gist')

    with op.batch_alter_table('stations_v4', schema='core') as batch_op:
        batch_op.drop_index('idx_stations_v4_geom', postgresql_using='gist')

    op.drop_table('stations_v4', schema='core')
    op.drop_table('jobs', schema='core')
    op.drop_table('networks', schema='core')
    with op.batch_alter_table('rasters', schema='gis') as batch_op:
        batch_op.drop_index('idx_rasters_bbox', postgresql_using='gist')

    op.drop_table('rasters', schema='gis')
    op.drop_table('antennas_v4', schema='core')
    # ### end Alembic commands ###
