"""Add erp_dbm to stations_v4

Revision ID: b3dd3e5c4c94
Revises: 5896fdaf3efb
Create Date: 2026-01-11 16:50:18.840926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3dd3e5c4c94'
down_revision = '5896fdaf3efb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations_v4', schema='core') as batch_op:
        batch_op.add_column(sa.Column('erp_dbm', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations_v4', schema='core') as batch_op:
        batch_op.drop_column('erp_dbm')

    # ### end Alembic commands ###
