"""initial schema

Revision ID: e2e9e951b691
Revises: 
Create Date: 2026-01-11 01:31:08.985523

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision = 'e2e9e951b691'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS auth")
    op.execute("CREATE SCHEMA IF NOT EXISTS core")
    op.execute("CREATE SCHEMA IF NOT EXISTS gis")
    op.execute("CREATE SCHEMA IF NOT EXISTS grid")
    op.execute("CREATE SCHEMA IF NOT EXISTS docs")
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='auth'
    )
    op.create_table('field_tiles',
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('layer', sa.Text(), nullable=False),
    sa.Column('z', sa.Integer(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('payload', sa.LargeBinary(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('revision_id', 'layer', 'z', 'x', 'y'),
    schema='grid'
    )
    op.create_table('email_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('service_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('current_revision_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('project_revisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('inputs_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['core.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('antenna',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('gain_dbd', sa.Float(), nullable=True),
    sa.Column('tilt_electrical_deg', sa.Float(), nullable=True),
    sa.Column('tilt_mechanical_deg', sa.Float(), nullable=True),
    sa.Column('pattern_h_file_id', sa.UUID(), nullable=True),
    sa.Column('pattern_v_file_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['revision_id'], ['core.project_revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('feedline',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('cable_type', sa.Text(), nullable=True),
    sa.Column('length_m', sa.Float(), nullable=True),
    sa.Column('attn_db_per_100m', sa.Float(), nullable=True),
    sa.Column('connector_losses_db', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['revision_id'], ['core.project_revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('interference_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('victim_station_ref', sa.Text(), nullable=False),
    sa.Column('relationship', sa.Text(), nullable=False),
    sa.Column('du_required_db', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['revision_id'], ['core.project_revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('opea_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('aerodrome_ref', sa.Text(), nullable=True),
    sa.Column('within_20km', sa.Boolean(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['revision_id'], ['core.project_revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('rni_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('eirp_w', sa.Float(), nullable=False),
    sa.Column('k_reflection', sa.Float(), nullable=False),
    sa.Column('s_limit_w_m2_public', sa.Float(), nullable=False),
    sa.Column('s_limit_w_m2_occ', sa.Float(), nullable=False),
    sa.Column('r_public_m', sa.Float(), nullable=False),
    sa.Column('r_occ_m', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['revision_id'], ['core.project_revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('station',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('tx_lat', sa.Float(), nullable=False),
    sa.Column('tx_lon', sa.Float(), nullable=False),
    sa.Column('ground_alt_m', sa.Float(), nullable=True),
    sa.Column('tower_height_agl_m', sa.Float(), nullable=True),
    sa.Column('frequency_mhz', sa.Float(), nullable=True),
    sa.Column('channel', sa.Integer(), nullable=True),
    sa.Column('bandwidth_khz', sa.Integer(), nullable=True),
    sa.Column('polarization', sa.Text(), nullable=True),
    sa.Column('datum', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['revision_id'], ['core.project_revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('transmitter',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('tx_power_w', sa.Float(), nullable=False),
    sa.Column('losses_internal_db', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['revision_id'], ['core.project_revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['revision_id'], ['core.project_revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='docs'
    )
    op.create_table('contours',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('contour_kind', sa.Text(), nullable=False),
    sa.Column('threshold_dbuvm', sa.Float(), nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4674, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, spatial_index=False), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['revision_id'], ['core.project_revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gis'
    )
    with op.batch_alter_table('contours', schema='gis') as batch_op:
        batch_op.create_index('idx_contours_geom', ['geom'], unique=False, postgresql_using='gist')

    op.create_table('contour_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contour_id', sa.UUID(), nullable=False),
    sa.Column('azimuth_deg', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('order_idx', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contour_id'], ['gis.contours.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gis'
    )
    op.create_table('interference_testpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4674, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, spatial_index=False), nullable=False),
    sa.Column('d_dbuvm', sa.Float(), nullable=False),
    sa.Column('u_dbuvm', sa.Float(), nullable=False),
    sa.Column('margin_db', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['core.interference_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gis'
    )
    with op.batch_alter_table('interference_testpoints', schema='gis') as batch_op:
        batch_op.create_index('idx_interference_testpoints_geom', ['geom'], unique=False, postgresql_using='gist')

    op.create_table('rni_critical_areas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rni_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4674, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, spatial_index=False), nullable=False),
    sa.Column('within_50m', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rni_id'], ['core.rni_assessments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gis'
    )
    with op.batch_alter_table('rni_critical_areas', schema='gis') as batch_op:
        batch_op.create_index('idx_rni_critical_areas_geom', ['geom'], unique=False, postgresql_using='gist')

    op.create_table('rni_zones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rni_id', sa.UUID(), nullable=False),
    sa.Column('zone_kind', sa.Text(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4674, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, spatial_index=False), nullable=False),
    sa.ForeignKeyConstraint(['rni_id'], ['core.rni_assessments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gis'
    )
    with op.batch_alter_table('rni_zones', schema='gis') as batch_op:
        batch_op.create_index('idx_rni_zones_geom', ['geom'], unique=False, postgresql_using='gist')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rni_zones', schema='gis') as batch_op:
        batch_op.drop_index('idx_rni_zones_geom', postgresql_using='gist')

    op.drop_table('rni_zones', schema='gis')
    with op.batch_alter_table('rni_critical_areas', schema='gis') as batch_op:
        batch_op.drop_index('idx_rni_critical_areas_geom', postgresql_using='gist')

    op.drop_table('rni_critical_areas', schema='gis')
    with op.batch_alter_table('interference_testpoints', schema='gis') as batch_op:
        batch_op.drop_index('idx_interference_testpoints_geom', postgresql_using='gist')

    op.drop_table('interference_testpoints', schema='gis')
    op.drop_table('contour_points', schema='gis')
    with op.batch_alter_table('contours', schema='gis') as batch_op:
        batch_op.drop_index('idx_contours_geom', postgresql_using='gist')

    op.drop_table('contours', schema='gis')
    op.drop_table('files', schema='docs')
    op.drop_table('transmitter', schema='core')
    op.drop_table('station', schema='core')
    op.drop_table('rni_assessments', schema='core')
    op.drop_table('opea_assessments', schema='core')
    op.drop_table('interference_cases', schema='core')
    op.drop_table('feedline', schema='core')
    op.drop_table('antenna', schema='core')
    op.drop_table('project_revisions', schema='core')
    op.drop_table('projects', schema='core')
    op.drop_table('email_tokens', schema='auth')
    op.drop_table('field_tiles', schema='grid')
    op.drop_table('users', schema='auth')
    # ### end Alembic commands ###
